# Error Handling

## **ERROR HANDLING TRY..CATCH**

when there's an error, the script stops immediately printing the error to the console

try...catch syntax construct allows to let the script continue to execute and handle the error separately without stopping

```js
    try {
        code to execute
    } catch (err) {
        error handling
    }
```

if the code in the try statement doesn't produce any errors, catch is ignored

if there are errors, try code stops (ignoring code after the error) control flows to catch
the (err) variable that will contain an error object with details about what happened.

`try..catch` can only work with **runtime errors**
      
**parse-time errors**  

the engine first reads the code (parses it) then runs it  
errors ocurred in parse-time are unrecoverable  

`try...catch` only works with run-time errors called exceptions
        
try...catch works synchronously

to catch an exception inside a scheduled function, try...catch must be inside that function

### **error object**

js generates an error object containing the details of an error that ocurred

**name**  

error name
`ReferenceError` for an undefined variable

**message**

textual message about error details
            
**stack**
                
current call stack, string with information about the sequence of nested calls that led to an error
    
### **optional catch binding**

recent addition to the language, may require polyfills

catch may omit the error object catch {} instead of catch (err) {}

if a method generates an error and makes the script die without an error message, we need to handle it with a try..catch

### **throw operator**

handles bugs, when code works but not as intended
        
`throw <error Object>`

javascript has many built-in constructors for standard errors
- Error
- SyntaxError
- ReferenceError
- TypeError
        
the name property for built-in errors is exactly the same as the constructor

### **rethrowing**

avoiding catch to get all errors from try naturally

catch should only process errors that it knows and rethrow all others
    
### **finally**

another code clause for the try...catch construct

```js
        try{executes code}
        catch(err){handles the error}
        finally{always executes}
```

variables are local inside try...catch...finally

`try...finally` without catch is possible, this is applied when we don't want to handle errors but make sure the process that started, finishes.
    
### **global catch**

environment specific, not implemented in the language level

## **CUSTOM ERRORS, EXTENDING ERROR**

extending Error

making sure to choose the right error to display with instanceof is useful for new inherited errors we'll create in the future

wrapping exceptions

        
