# Promises, Async & Await

## **INTRODUCTION**

functions are provided by environments that allow to scheduled asynchronous actions

### asynchronous actions

they start now, finish later
    
if there's code below an asyncrhonous function, it doesn't wait for the function to finish

### callback function

executes when the asynchronous function completes

### onload event

executes a function after the script is loaded and executed

### nested callback 

allows to load two scripts sequentially
    
### callback hell or pyramid of doom

too many nested callbacks
    
### avoiding a pyramid of nested calls 

making every action a standalone function

## **PROMISE**

producing code  
executes, returns a value after some time
    
consuming code  
wants to use the returned value of the producing code

**promise**  
special javascript object linking producing code and consuming code together
    
### **constructor syntax**

```js
let promise = new Promise(function(resolve, reject)){
  executor (producing code)
}
```

function passed to the promise its called the ***executor***

arguments are callbacks provided by javascript itself

when the executor returns a value (sooner or later), it calls one of the callback arguments.

**resolve(value)**  
if the job is finished, the returned value is passed to resolve

**reject(value)**  
if an error has occurred, error object is passed to reject
    
executor runs automatic when a new promise is constructed

finishes execution successfully, and the promise will callback resolve(value)

execution fails, the promise will callback reject(error)

### **promise object internal properties**

**state**  
initially a value of 'pending'

'***fulfilled***' when resolve is called

'***rejected***' when reject is called

**result** 
initially undefined
            
becomes ***value*** when resolve(value) is called

becomes ***error*** when reject(error) is called
        
- new constructor calls the executor automatically
- executor performs a task that takes time
- executor calls resolve or reject (predefined functions in js) to update the state of the promise object

initially pending promise

resolved or rejected promise (settled)

can only have one single result or error,

further calls of resolve and reject, will be ignored after the first one

resolve/reject expects only one argument, ignores the rest

any type of argument could be passed to reject, but error objects are best practice

**immediately calling resolve/reject**

- a tasks starts, but result has already been cached, immediately resolving the promise
    
`then catch finally methods` are used to access the promise object properties (**state, result**)

consumer code can be registered using methods .then and .catch

### **then**

**syntax**

```js
promise.then {
  function(result){code that handles a successful result}
  function(error){code that handles an error}
}
```
        
first argument of then is a function that runs when the promise is resolved (fullfilled)

second argument is a function that runs when the promise is rejected

```js
// only handling results
promise.then(function(result){})

// only handling errors
promise.then(null, function(error){})
            
// or
promise.catch(function)
```

### **catch**

promise.catch(function)

only handles a rejected promise

### **finally**
        
finally runs always when a promise is settled (resolved or rejected)

`promise.finally(f)` is the same as `promise.then(f, f)`

setups a handler to perform cleanup/finalization after the task is completed or rejected

> finally ensures to execute before then or catch

provides generic cleanup no matter what the outcome of a promise is

finally never returns anything (if it does it is silently ignored).

exception is when a finally handler throws an error. If finally throws an error, execution goes to the nearest error handler.
    
then, catch, finally wait for a promise to settle.
        
## **PROMISES CHAINING**

chaining asynchronous tasks to be performed one after another

```js
new Promise(function(resolve, reject) {
  setTimeout(() => resolve(1), 1000);
}).then(function(result) {
  console.log(result);
  return result * 2;
}).then(function(result) {
  console.log(result);
  return result * 2;
}).then(function(result) {
  console.log(result);
  return result * 2;
})
```

result is passed through the chain of .then handlers

result is computed immediately, just the first resolve has a delay of 1s

### **returning promises**

a handler `.then(handler)` may create and return a promise

further handlers wait until it settles and then get its result

```js
new Promise(function(resolve, reject) {
  setTimeout(() => resolve(1), 1000);
}).then(function(result) {
  console.log(result);
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(result *2), 1000);
  });
}).hen(function(result) {
  console.log(result);
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(result * 2), 1000);
  })
}).then(function(result) {
  console.log(result)
});
```

first then will show result, then return a new promise and resolve it after the delay,

the result is the same as previous, but now each then takes its own time

by returning a new promise in each then, each result can take some time to execute without breaking the chain

then syntax can be simplified with arrow functions

```js
.then(function(result){return result})
.then(result => return result)
```

### **thenable**

an arbitraty object that has a .then method

treated the same as a promise

object that is promise-compatible

they extend native promise objects in third-party libraries

### **fetch**

`let promise = fetch(url);`
    
fetch makes a network request to the url and returns a promise

the remote server resolves the promise with a response object with the response headers but before the full response is downloaded
        
the response object returned from fetch contains methods

`response.text()` reads the full response

returns a promise when full text is downloaded

`response.json()` reads remote data and parses it as JSON

`fetch('url')`

.then(response => return response.text())  
.then(text => console.log(text));  
        
an asynchronous action should always return a new promise as best practice

## **ERROR HANDLING WITH PROMISES**

when a promise rejects, control flow jumps to the closes rejection handler

```js
fetch('badURL')
  .then(response => response.json())
  .catch(err => console.log(err))
```

appending a catch to the end of the chain, will guarantee the error will be catched

```js
new Promise((resolve, reject) => {
  resolve('ok');
}).then((result) => {
  throw new Error('whoops!');
}).catch(console.log);
```

unhandled promise rejections cause the script to stop

```js
window.addEventListener('unhandledrejection', function(event) {
  console.log(event.promise);
  console.log(event.reason);
});

new Promise(function() {
  throw new Error('whoops!');
});
```

`unhandledrejection` is an event part of the HTML standard

## **PROMISE API**

6 static methods in the promise class

### **Promise.all**

many promises execute in parallel and wait until all of them are ready

```js
let promise = Promise.all(iterable);
```

takes an iterable (array of promises) and returns a new promise

the new promise resolves when all listed promises are resolved 

if any of the promises is rejected, the promise returned by Promise.all rejects with an error
        
Promise.all accepts other values besides an iterable (primitives are passed as is)
    
### **Promise.allSettled**

new addition to the language

waits for all promises to settle regardless of the status

### **Promise.race**

similar to Promise.all but waits for the first settled promise, and gets its result or error

```js
Promise.race([
  new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),
  new Promise((resolve, reject) => setTimeout(() => reject(new Error('whoops!')), 2000)),
  new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000))
]).then(console.log);
```

only the fastest promise to resolve or reject is included, the rest are ignored
    
### **Promise.any**

```js
let promise = Promise.any(iterable);
```

similar to race, waits for the first fulfilled promise, 

further results are ignored

if a promise rejects, it waits until a promise resolves

if all given promises are rejected, returned promise is rejected with AggregatorError

```js
Promise.any([
  new Promise((resolve, reject) => setTimeout(() => reject(new Error('ouch!')), 1000)),
  new Promise(resolve, reject) => setTimeout(() => reject(new Error('whoops!')), 2000)
]).atch(error => {
  console.log(error.constructor.name);
  console.log(error.errors[0]);
  console.log(error.errors[1]);
});
```

older incompatible methods with async/await

### **Promise.resolve(value)**

creates a resolved promise with the result value
    
### **Promise.reject(error)**

creates a rejected promise with an error

## **PROMISIFICATION**

converts a function that accepts a callback into a function that returns a promise

## **MICROTASKS**

even when a promise is immediately resolve, code below .then .catch . finally will execute first

ECMA standard specifies an internal queue PromiseJobs often referred as the microtask queue (v8 term)

queue is first-in-first-out

execution of a task is initiated only when nothing else is running

promise handlers always go through this internal queue

a chain of .then.catch.finally each one of them is executed asynchronously 

chaining code in .then puts code in the queue

unhandled rejection occurs when a promise error is not handled at the end of the microtask queue

if we forget to handle a rejected promise with .catch,

setting unhandledrejecction event tells js to check if the microtask queue is empty,

the engine examines promises, and if any have a status:rejected, the event triggers

## **ASYNC/AWAIT**

special syntax to work with promises 

### **async functions**

```js
async function f() {
  return 1;
}
```
an async function always returns a promise

other values are wrapped in a resolved promise automatically
    
### **await**

```js
let value = await promise;
```
    
makes js to wait until the promise settles, to return its result

```js
async function f() {
  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve('done'), 1000)
  });

  let result = await promise;
  waits until the promsie resolves

  console.log(result);
}

f();
```

await suspends the function execution until the promise settles, then resumes with the promise result

the javascript engine can do other jobs in the meantime, execute other scripts, handle events

more elegant syntax than promise.then

await keyword can't be used in a regular function

modern browsers allow top-level await in modules without modules, an async 

### **await accepts thenables**

thenables are third-party objects that may not be a promise, but promise-compatible (have a callable then method)

```js
class Thenable {
  constructor(num) {
    this.num = num;
  }
  then(resolve, reject) {
    console.log(resolve);
    setTimeout(() => resolve(this.mum * 2), 1000);
  }
}

async function f() {
  let result = await new Thenable(1);
  console.log(result);
}

f();
```

### **methods can be async inside classes**

```js
class Waiter {
  async wait() {
    return awai Promise.resolve(1);
  }
}

new Waiter()
  .wait()
  .then(console.log); the same as (result => console.log(result));
```
        
### **error handling**

if promise resolves then await promise returns the result

if the promise is rejected, it throws error just as a throw statement

async/await generally won't use .then because await handles the waiting for us
 
try..catch regular instead of .catch

.then/.catch is used at the top level of the codem outside any async function

    